import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.scss';
import { Header } from '@/widgets/header';
import { Footer } from '@/widgets/footer';

const manropeSans = Manrope({
  variable: '--font-family',
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'Arbolit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manropeSans.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
