import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import './globals.css';

const manropeSans = Manrope({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Arbolit',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${manropeSans.variable} ${manropeSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
